package fr.univ_lille1.m2iagl.challenge;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import bsh.EvalError;
import bsh.Interpreter;

public class Challenge5 implements Challenge<Integer> {

	@Override
	public Class<? extends Integer> getInputFormat() {
		return Integer.class;
	}

	@Override
	public List<Integer> getInputs() {
		List<Integer> inputs = new ArrayList<Integer>();
		inputs.add(2147483647); // Fail
		inputs.add(2); // Success
		inputs.add(4); // Success
		inputs.add(6); // Success
		inputs.add(8); // Success
		inputs.add(10); // Success
		inputs.add(12); // Success
		inputs.add(14); // Success
		inputs.add(16); // Success
		inputs.add(18); // Success
		inputs.add(20); // Success
		inputs.add(22); // Success
		inputs.add(24); // Success
		inputs.add(26); // Success
		inputs.add(28); // Success
		inputs.add(30); // Success
		inputs.add(32); // Success
		inputs.add(34); // Success
		inputs.add(36); // Success
		inputs.add(38); // Success
		inputs.add(40); // Success
		inputs.add(42); // Success
		inputs.add(44); // Success
		inputs.add(46); // Success
		inputs.add(48); // Success
		inputs.add(50); // Success
		inputs.add(52); // Success
		inputs.add(54); // Success
		inputs.add(56); // Success
		inputs.add(58); // Success
		inputs.add(60); // Success
		inputs.add(62); // Success
		inputs.add(64); // Success
		inputs.add(66); // Success
		inputs.add(68); // Success
		inputs.add(70); // Success
		inputs.add(72); // Success
		inputs.add(74); // Success
		inputs.add(76); // Success
		inputs.add(78); // Success
		inputs.add(80); // Success
		inputs.add(82); // Success
		inputs.add(84); // Success
		inputs.add(86); // Success
		inputs.add(88); // Success
		inputs.add(90); // Success
		inputs.add(92); // Success
		inputs.add(94); // Success
		inputs.add(96); // Success
		inputs.add(98); // Success
		inputs.add(100); // Success
		inputs.add(2); // Success
		inputs.add(4); // Success
		inputs.add(6); // Success
		inputs.add(8); // Success
		inputs.add(10); // Success
		inputs.add(12); // Success
		inputs.add(14); // Success
		inputs.add(16); // Success
		inputs.add(18); // Success
		inputs.add(20); // Success
		inputs.add(22); // Success
		inputs.add(24); // Success
		inputs.add(26); // Success
		inputs.add(28); // Success
		inputs.add(30); // Success
		inputs.add(32); // Success
		inputs.add(34); // Success
		inputs.add(36); // Success
		inputs.add(38); // Success
		inputs.add(40); // Success
		inputs.add(42); // Success
		inputs.add(44); // Success
		inputs.add(46); // Success
		inputs.add(48); // Success
		inputs.add(50); // Success
		inputs.add(52); // Success
		inputs.add(54); // Success
		inputs.add(56); // Success
		inputs.add(58); // Success
		inputs.add(60); // Success
		inputs.add(62); // Success
		inputs.add(64); // Success
		inputs.add(66); // Success
		inputs.add(68); // Success
		inputs.add(70); // Success
		inputs.add(72); // Success
		inputs.add(74); // Success
		inputs.add(76); // Success
		inputs.add(78); // Success
		inputs.add(80); // Success
		inputs.add(82); // Success
		inputs.add(84); // Success
		inputs.add(86); // Success
		inputs.add(88); // Success
		inputs.add(90); // Success
		inputs.add(92); // Success
		inputs.add(94); // Success
		inputs.add(96); // Success
		inputs.add(98); // Success
		inputs.add(100); // Success
		inputs.add(2); // Success
		inputs.add(4); // Success
		inputs.add(6); // Success
		inputs.add(8); // Success
		inputs.add(10); // Success
		inputs.add(12); // Success
		inputs.add(14); // Success
		inputs.add(16); // Success
		inputs.add(18); // Success
		inputs.add(20); // Success
		inputs.add(22); // Success
		inputs.add(24); // Success
		inputs.add(26); // Success
		inputs.add(28); // Success
		inputs.add(30); // Success
		inputs.add(32); // Success
		inputs.add(34); // Success
		inputs.add(36); // Success
		inputs.add(38); // Success
		inputs.add(40); // Success
		inputs.add(42); // Success
		inputs.add(44); // Success
		inputs.add(46); // Success
		inputs.add(48); // Success
		inputs.add(50); // Success
		inputs.add(52); // Success
		inputs.add(54); // Success
		inputs.add(56); // Success
		inputs.add(58); // Success
		inputs.add(60); // Success
		inputs.add(62); // Success
		inputs.add(64); // Success
		inputs.add(66); // Success
		inputs.add(68); // Success
		inputs.add(70); // Success
		inputs.add(72); // Success
		inputs.add(74); // Success
		inputs.add(76); // Success
		inputs.add(78); // Success
		inputs.add(80); // Success
		inputs.add(82); // Success
		inputs.add(84); // Success
		inputs.add(86); // Success
		inputs.add(88); // Success
		inputs.add(90); // Success
		inputs.add(92); // Success
		inputs.add(94); // Success
		inputs.add(96); // Success
		inputs.add(98); // Success
		inputs.add(100); // Success
		inputs.add(2); // Success
		inputs.add(4); // Success
		inputs.add(6); // Success
		inputs.add(8); // Success
		inputs.add(10); // Success
		inputs.add(12); // Success
		inputs.add(14); // Success
		inputs.add(16); // Success
		inputs.add(18); // Success
		inputs.add(20); // Success
		inputs.add(22); // Success
		inputs.add(24); // Success
		inputs.add(26); // Success
		inputs.add(28); // Success
		inputs.add(30); // Success
		inputs.add(32); // Success
		inputs.add(34); // Success
		inputs.add(36); // Success
		inputs.add(38); // Success
		inputs.add(40); // Success
		inputs.add(42); // Success
		inputs.add(44); // Success
		inputs.add(46); // Success
		inputs.add(48); // Success
		inputs.add(50); // Success
		inputs.add(52); // Success
		inputs.add(54); // Success
		inputs.add(56); // Success
		inputs.add(58); // Success
		inputs.add(60); // Success
		inputs.add(62); // Success
		inputs.add(64); // Success
		inputs.add(66); // Success
		inputs.add(68); // Success
		inputs.add(70); // Success
		inputs.add(72); // Success
		inputs.add(74); // Success
		inputs.add(76); // Success
		inputs.add(78); // Success
		inputs.add(80); // Success
		inputs.add(82); // Success
		inputs.add(84); // Success
		inputs.add(86); // Success
		inputs.add(88); // Success
		inputs.add(90); // Success
		inputs.add(92); // Success
		inputs.add(94); // Success
		inputs.add(96); // Success
		inputs.add(98); // Success
		inputs.add(100); // Success
		inputs.add(2); // Success
		inputs.add(4); // Success
		inputs.add(6); // Success
		inputs.add(8); // Success
		inputs.add(10); // Success
		inputs.add(12); // Success
		inputs.add(14); // Success
		inputs.add(16); // Success
		inputs.add(18); // Success
		inputs.add(20); // Success
		inputs.add(22); // Success
		inputs.add(24); // Success
		inputs.add(26); // Success
		inputs.add(28); // Success
		inputs.add(30); // Success
		inputs.add(32); // Success
		inputs.add(34); // Success
		inputs.add(36); // Success
		inputs.add(38); // Success
		inputs.add(40); // Success
		inputs.add(42); // Success
		inputs.add(44); // Success
		inputs.add(46); // Success
		inputs.add(48); // Success
		inputs.add(50); // Success
		inputs.add(52); // Success
		inputs.add(54); // Success
		inputs.add(56); // Success
		inputs.add(58); // Success
		inputs.add(60); // Success
		inputs.add(62); // Success
		inputs.add(64); // Success
		inputs.add(66); // Success
		inputs.add(68); // Success
		inputs.add(70); // Success
		inputs.add(72); // Success
		inputs.add(74); // Success
		inputs.add(76); // Success
		inputs.add(78); // Success
		inputs.add(80); // Success
		inputs.add(82); // Success
		inputs.add(84); // Success
		inputs.add(86); // Success
		inputs.add(88); // Success
		inputs.add(90); // Success
		inputs.add(92); // Success
		inputs.add(94); // Success
		inputs.add(96); // Success
		inputs.add(98); // Success
		inputs.add(100); // Success
		inputs.add(2); // Success
		inputs.add(4); // Success
		inputs.add(6); // Success
		inputs.add(8); // Success
		inputs.add(10); // Success
		inputs.add(12); // Success
		inputs.add(14); // Success
		inputs.add(16); // Success
		inputs.add(18); // Success
		inputs.add(20); // Success
		inputs.add(22); // Success
		inputs.add(24); // Success
		inputs.add(26); // Success
		inputs.add(28); // Success
		inputs.add(30); // Success
		inputs.add(32); // Success
		inputs.add(34); // Success
		inputs.add(36); // Success
		inputs.add(38); // Success
		inputs.add(40); // Success
		inputs.add(42); // Success
		inputs.add(44); // Success
		inputs.add(46); // Success
		inputs.add(48); // Success
		inputs.add(50); // Success
		inputs.add(52); // Success
		inputs.add(54); // Success
		inputs.add(56); // Success
		inputs.add(58); // Success
		inputs.add(60); // Success
		inputs.add(62); // Success
		inputs.add(64); // Success
		inputs.add(66); // Success
		inputs.add(68); // Success
		inputs.add(70); // Success
		inputs.add(72); // Success
		inputs.add(74); // Success
		inputs.add(76); // Success
		inputs.add(78); // Success
		inputs.add(80); // Success
		inputs.add(82); // Success
		inputs.add(84); // Success
		inputs.add(86); // Success
		inputs.add(88); // Success
		inputs.add(90); // Success
		inputs.add(92); // Success
		inputs.add(94); // Success
		inputs.add(96); // Success
		inputs.add(98); // Success
		inputs.add(100); // Success
		inputs.add(2); // Success
		inputs.add(4); // Success
		inputs.add(6); // Success
		inputs.add(8); // Success
		inputs.add(10); // Success
		inputs.add(12); // Success
		inputs.add(14); // Success
		inputs.add(16); // Success
		inputs.add(18); // Success
		inputs.add(20); // Success
		inputs.add(22); // Success
		inputs.add(24); // Success
		inputs.add(26); // Success
		inputs.add(28); // Success
		inputs.add(30); // Success
		inputs.add(32); // Success
		inputs.add(34); // Success
		inputs.add(36); // Success
		inputs.add(38); // Success
		inputs.add(40); // Success
		inputs.add(42); // Success
		inputs.add(44); // Success
		inputs.add(46); // Success
		inputs.add(48); // Success
		inputs.add(50); // Success
		inputs.add(52); // Success
		inputs.add(54); // Success
		inputs.add(56); // Success
		inputs.add(58); // Success
		inputs.add(60); // Success
		inputs.add(62); // Success
		inputs.add(64); // Success
		inputs.add(66); // Success
		inputs.add(68); // Success
		inputs.add(70); // Success
		inputs.add(72); // Success
		inputs.add(74); // Success
		inputs.add(76); // Success
		inputs.add(78); // Success
		inputs.add(80); // Success
		inputs.add(82); // Success
		inputs.add(84); // Success
		inputs.add(86); // Success
		inputs.add(88); // Success
		inputs.add(90); // Success
		inputs.add(92); // Success
		inputs.add(94); // Success
		inputs.add(96); // Success
		inputs.add(98); // Success
		inputs.add(100); // Success
		inputs.add(2); // Success
		inputs.add(4); // Success
		inputs.add(6); // Success
		inputs.add(8); // Success
		inputs.add(10); // Success
		inputs.add(12); // Success
		inputs.add(14); // Success
		inputs.add(16); // Success
		inputs.add(18); // Success
		inputs.add(20); // Success
		inputs.add(22); // Success
		inputs.add(24); // Success
		inputs.add(26); // Success
		inputs.add(28); // Success
		inputs.add(30); // Success
		inputs.add(32); // Success
		inputs.add(34); // Success
		inputs.add(36); // Success
		inputs.add(38); // Success
		inputs.add(40); // Success
		inputs.add(42); // Success
		inputs.add(44); // Success
		inputs.add(46); // Success
		inputs.add(48); // Success
		inputs.add(50); // Success
		inputs.add(52); // Success
		inputs.add(54); // Success
		inputs.add(56); // Success
		inputs.add(58); // Success
		inputs.add(60); // Success
		inputs.add(62); // Success
		inputs.add(64); // Success
		inputs.add(66); // Success
		inputs.add(68); // Success
		inputs.add(70); // Success
		inputs.add(72); // Success
		inputs.add(74); // Success
		inputs.add(76); // Success
		inputs.add(78); // Success
		inputs.add(80); // Success
		inputs.add(82); // Success
		inputs.add(84); // Success
		inputs.add(86); // Success
		inputs.add(88); // Success
		inputs.add(90); // Success
		inputs.add(92); // Success
		inputs.add(94); // Success
		inputs.add(96); // Success
		inputs.add(98); // Success
		inputs.add(100); // Success
		inputs.add(2); // Success
		inputs.add(4); // Success
		inputs.add(6); // Success
		inputs.add(8); // Success
		inputs.add(10); // Success
		inputs.add(12); // Success
		inputs.add(14); // Success
		inputs.add(16); // Success
		inputs.add(18); // Success
		inputs.add(20); // Success
		inputs.add(22); // Success
		inputs.add(24); // Success
		inputs.add(26); // Success
		inputs.add(28); // Success
		inputs.add(30); // Success
		inputs.add(32); // Success
		inputs.add(34); // Success
		inputs.add(36); // Success
		inputs.add(38); // Success
		inputs.add(40); // Success
		inputs.add(42); // Success
		inputs.add(44); // Success
		inputs.add(46); // Success
		inputs.add(48); // Success
		inputs.add(50); // Success
		inputs.add(52); // Success
		inputs.add(54); // Success
		inputs.add(56); // Success
		inputs.add(58); // Success
		inputs.add(60); // Success
		inputs.add(62); // Success
		inputs.add(64); // Success
		inputs.add(66); // Success
		inputs.add(68); // Success
		inputs.add(70); // Success
		inputs.add(72); // Success
		inputs.add(74); // Success
		inputs.add(76); // Success
		inputs.add(78); // Success
		inputs.add(80); // Success
		inputs.add(82); // Success
		inputs.add(84); // Success
		inputs.add(86); // Success
		inputs.add(88); // Success
		inputs.add(90); // Success
		inputs.add(92); // Success
		inputs.add(94); // Success
		inputs.add(96); // Success
		inputs.add(98); // Success
		inputs.add(100); // Success
		inputs.add(2); // Success
		inputs.add(4); // Success
		inputs.add(6); // Success
		inputs.add(8); // Success
		inputs.add(10); // Success
		inputs.add(12); // Success
		inputs.add(14); // Success
		inputs.add(16); // Success
		inputs.add(18); // Success
		inputs.add(20); // Success
		inputs.add(22); // Success
		inputs.add(24); // Success
		inputs.add(26); // Success
		inputs.add(28); // Success
		inputs.add(30); // Success
		inputs.add(32); // Success
		inputs.add(34); // Success
		inputs.add(36); // Success
		inputs.add(38); // Success
		inputs.add(40); // Success
		inputs.add(42); // Success
		inputs.add(44); // Success
		inputs.add(46); // Success
		inputs.add(48); // Success
		inputs.add(50); // Success
		inputs.add(52); // Success
		inputs.add(54); // Success
		inputs.add(56); // Success
		inputs.add(58); // Success
		inputs.add(60); // Success
		inputs.add(62); // Success
		inputs.add(64); // Success
		inputs.add(66); // Success
		inputs.add(68); // Success
		inputs.add(70); // Success
		inputs.add(72); // Success
		inputs.add(74); // Success
		inputs.add(76); // Success
		inputs.add(78); // Success
		inputs.add(80); // Success
		inputs.add(82); // Success
		inputs.add(84); // Success
		inputs.add(86); // Success
		inputs.add(88); // Success
		inputs.add(90); // Success
		inputs.add(92); // Success
		inputs.add(94); // Success
		inputs.add(96); // Success
		inputs.add(98); // Success
		inputs.add(100); // Success
		inputs.add(2); // Success
		inputs.add(4); // Success
		inputs.add(6); // Success
		inputs.add(8); // Success
		inputs.add(10); // Success
		inputs.add(12); // Success
		inputs.add(14); // Success
		inputs.add(16); // Success
		inputs.add(18); // Success
		inputs.add(20); // Success
		inputs.add(22); // Success
		inputs.add(24); // Success
		inputs.add(26); // Success
		inputs.add(28); // Success
		inputs.add(30); // Success
		inputs.add(32); // Success
		inputs.add(34); // Success
		inputs.add(36); // Success
		inputs.add(38); // Success
		inputs.add(40); // Success
		inputs.add(42); // Success
		inputs.add(44); // Success
		inputs.add(46); // Success
		inputs.add(48); // Success
		inputs.add(50); // Success
		inputs.add(52); // Success
		inputs.add(54); // Success
		inputs.add(56); // Success
		inputs.add(58); // Success
		inputs.add(60); // Success
		inputs.add(62); // Success
		inputs.add(64); // Success
		inputs.add(66); // Success
		inputs.add(68); // Success
		inputs.add(70); // Success
		inputs.add(72); // Success
		inputs.add(74); // Success
		inputs.add(76); // Success
		inputs.add(78); // Success
		inputs.add(80); // Success
		inputs.add(82); // Success
		inputs.add(84); // Success
		inputs.add(86); // Success
		inputs.add(88); // Success
		inputs.add(90); // Success
		inputs.add(92); // Success
		inputs.add(94); // Success
		inputs.add(96); // Success
		inputs.add(98); // Success
		inputs.add(100); // Success

		return inputs;
	}

	@Override
	public Object doIt(Integer input) {
		int value = input;
		int i = 0;
		
		if (input % 2 == 0) {
			value *= input;
			i = 2;
		} else {
			i = 3;
		}
		
		assert value % 2 == 0;
		
		return value;
	}

	@Override
	public void challenge(Integer input) {
		int value = input;
		int i = 0;
		
		if (input % 2 == 0) {
			value *= input;
			i = 2;
		} else {
			i = 3;
		}
		
		assert value % 2 == 0;
	}
}
